### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ctoxy**
## Purpose
first base pull request with a basic structure 

## Approach
_in order to show a basic template and feature about the project motus

#### Open Questions and Pre-Merge TODOs
- 

## Learning
_angular basics github 

_

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by BenbachirAzzedine — APPROVED** [review]
Nice!!!

**Review by ArnaudPichot — APPROVED** [review]
c'est cool on pourra presenter un truc graphique demain

**Review by GuillaumeCabaret — APPROVED** [review]
NICE mais attention la prochaine fois pour l’accessibilité

**Comment by mateo-m** [comment]
Yes ! Faudra qu'on améliore l'accéssibilité

**Review by mateo-m — APPROVED** [review]
Yes

**Review by BertrandBurel — APPROVED** [review]
OK, ça passe pour moi

**Pull request merged**
